version: "3.9"

services:
  api:
    image: cookin-up-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/cookin_up
    env_file:
      - .env
